// models/Caregiver.js
const mongoose = require('mongoose');

const CaregiverSchema = new mongoose.Schema({
  status: { type: Number, required: true },
  datetime: { type: Date, default: Date.now },
  metadata: [{
    FirstName: { type: String, required: true },
    LastName: { type: String, required: true },
    MiddleName: { type: String, default: '' },
    AideInitial: { type: String, default: '' },
    Gender: { type: String, required: true },
    DateofBirth: { type: String, required: true },
    AideCode: { type: String, required: true },
    IVREmployeeID: { type: String, default: '' },
    ALternateAideCode: { type: String, default: '' },
    Ethnicity: { type: String, default: '' },
    SSN: { type: String, required: true },
    MaritalStatus: { type: String, default: '' },
    Discipline: { type: String, default: '' },
    Dependents: { type: String, default: '' },
    AidePicture: { type: String, default: 'No' },
    CountryofBirth: { type: String, default: '' },
    RehireDate: { type: String, default: '' },
    MobileID: { type: String, default: '' },
    MobileIDStatus: { type: String, default: 'Active' },
    CaregiverMobileAppAvailability: { type: String, default: 'No' },
    ReferralSource: { type: String, default: '' },
    ReferralPerson: { type: String, default: '' },
    ApplicationDate: { type: String, required: true },
    HiringStatus: { type: String, required: true },
    Status: { type: String, required: true },
    Reference1: { type: String, default: '' },
    Reference2: { type: String, default: '' },
    TerminatedDate: { type: String, default: '' },
    Sent105: { type: String, default: 'NO' },
    FirstWorkDate: { type: String, required: true },
    LastWorkDate: { type: String, required: true },
    StateRegistry: { type: String, default: '' },
    RegistryDate: { type: String, default: '' },
    Location: { type: String, default: '' },
    Branch: { type: String, default: '' },
    CaregiverTeam: { type: String, default: '' },
    EmployeeID: { type: String, default: '' },
    Address1: { type: String, required: true },
    Address2: { type: String, default: '' },
    City: { type: String, required: true },
    State: { type: String, required: true },
    ZipCode: { type: String, required: true },
    Phone: { type: String, required: true },
    Phone2: { type: String, default: '' },
    Phone3: { type: String, default: '' },
    Zip4: { type: String, default: '' },
    Emergency1Name: { type: String, default: '' },
    Emergency1Relationship: { type: String, default: '' },
    Emergency1Address: { type: String, default: '' },
    Emergency1Phone1: { type: String, default: '' },
    Emergency1Phone2: { type: String, default: '' },
    Emergency2Name: { type: String, default: '' },
    Emergency2Relationship: { type: String, default: '' },
    Emergency2Address: { type: String, default: '' },
    Emergency2Phone1: { type: String, default: '' },
    Emergency2Phone2: { type: String, default: '' },
    Language1: { type: String, default: '' },
    Language2: { type: String, default: '' },
    Language3: { type: String, default: '' },
    Language4: { type: String, default: '' },
    DocumentAB: { type: String, default: '' },
    DocumentC: { type: String, default: '' },
    I9FormExpirationDate: { type: String, default: '' },
    I9Notes: { type: String, default: '' },
    CriminalBackgroundSentOutDate: { type: String, default: '' },
    CriminalBackgroundSentOutResult: { type: String, default: '' },
    SentOutReceivedOn: { type: String, default: '' },
    CriminalBackgroundSecondSubmissionDate: { type: String, default: '' },
    CriminalBackgroundSecondSubmissionResult: { type: String, default: '' },
    SecondSubmissionReceivedOn: { type: String, default: '' },
    CriminalBackgroundThirdSubmissionDate: { type: String, default: '' },
    CriminalBackgroundThirdSubmissionResult: { type: String, default: '' },
    ThirdSubmissionReceivedOn: { type: String, default: '' },
    LastEmploymentAgency: { type: String, default: '' },
    LastEmploymentDateFrom: { type: String, default: '' },
    LastEmploymentDateTo: { type: String, default: '' },
    CoCode: { type: String, default: '' },
    FedExemption: { type: String, default: '' },
    RateType: { type: String, default: '' },
    PensionProfitSharing: { type: String, default: '' },
    ExemptionFromOvertime: { type: String, default: '' },
    DirectDeposit: { type: String, default: '' },
    NycResident: { type: String, default: '' },
    Employee1099: { type: String, default: '' },
    UnionReduction: { type: String, default: '' },
    MedicalDeductionCode: { type: String, default: '' },
    PayCycle: { type: String, default: '' },
    PreferredContactMethod: { type: String, default: '' },
    NotificationEmail: { type: String, default: '' },
    NotificationTextMessaging: { type: String, default: '' },
    NotificationVoiceMail: { type: String, default: '' },
    pwd: { type: String, required: true },
    user_id: { type: String, required: true }
    
  }],
});

module.exports = mongoose.model('Caregiver', CaregiverSchema);